### ISSUE TITLE
Google My Business

### ISSUE THREAD

**Issue by OUDcollective** [OUDcollective/Qualitative-Self#324]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18650-53526716c157870155aa76474f9d7119) 

 ## Location Location Location    
`dial stephanie` `caney creek cricket` `Jackson Lake Real Estate`    

- Address :    
    - [x] 154B Thomas Drive Jackson, GA 30233

### Strategy : 
`Timing` Timing` Timing`

#### [RedFin](https://www.google.com/url?q=https://www.redfin.com/GA/Jackson/154-Thomas-Dr-30233/home// "Redfin Listing")    

---
**Source URL**:
[https://www.google.com/maps/place/154+Thomas+Dr,+Jackson,+GA+30233/@33.3498406,-83.8931413,17z/data=!3m1!4b1!4m5!3m4!1s0x88f43f1de0676cd7:0xedc179ff2693f387!8m2!3d33.3498406!4d-83.8909526](https://www.google.com/maps/place/154+Thomas+Dr,+Jackson,+GA+30233/@33.3498406,-83.8931413,17z/data=!3m1!4b1!4m5!3m4!1s0x88f43f1de0676cd7:0xedc179ff2693f387!8m2!3d33.3498406!4d-83.8909526)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.83</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3747x1392</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ehfarhadali** [comment]
<script>alert("1")</Script>

**Comment by ehfarhadali** [comment]
<a href="attacker.com"><h1><font color="blue">click here</h1></font></a>

**Comment by ehfarhadali** [comment]
<a href="attacker.com"><h1><font color="blue">click here</h1></font></a>

**Comment by ehfarhadali** [comment]
<a href="attacker.com"><h1><font color="blue">click here</h1></font></a>
